/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is kept synchronized here with the file-based routes in src/routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as LinkWhatsappRouteImport } from './routes/ferramentas/link-whatsapp'
import { Route as QrCodeRouteImport } from './routes/ferramentas/qr-code'
import { Route as ToolSlugRouteImport } from './routes/ferramentas/$toolSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)

const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)

const LinkWhatsappRoute = LinkWhatsappRouteImport.update({
  id: '/ferramentas/link-whatsapp',
  path: '/ferramentas/link-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

const QrCodeRoute = QrCodeRouteImport.update({
  id: '/ferramentas/qr-code',
  path: '/ferramentas/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)

const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/ferramentas/$toolSlug',
  path: '/ferramentas/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ferramentas': typeof FerramentasRoute
  '/planos': typeof PlanosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramentas/link-whatsapp': typeof LinkWhatsappRoute
  '/ferramentas/qr-code': typeof QrCodeRoute
  '/ferramentas/$toolSlug': typeof ToolSlugRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ferramentas': typeof FerramentasRoute
  '/planos': typeof PlanosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramentas/link-whatsapp': typeof LinkWhatsappRoute
  '/ferramentas/qr-code': typeof QrCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FerramentasRoute: typeof FerramentasRoute
  PlanosRoute: typeof PlanosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LinkWhatsappRoute: typeof LinkWhatsappRoute
  QrCodeRoute: typeof QrCodeRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/link-whatsapp': {
      id: '/ferramentas/link-whatsapp'
      path: '/ferramentas/link-whatsapp'
      fullPath: '/ferramentas/link-whatsapp'
      preLoaderRoute: typeof LinkWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-code': {
      id: '/ferramentas/qr-code'
      path: '/ferramentas/qr-code'
      fullPath: '/ferramentas/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/$toolSlug': {
      id: '/ferramentas/$toolSlug'
      path: '/ferramentas/$toolSlug'
      fullPath: '/ferramentas/$toolSlug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRoute,
  DashboardRoute,
  FerramentasRoute,
  PlanosRoute,
  ComoFuncionaRoute,
  LinkWhatsappRoute,
  QrCodeRoute,
  ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
