/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It is kept synchronized here with the file-based routes in src/routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as LinkWhatsappRouteImport } from './routes/ferramentas/link-whatsapp'
import { Route as QrCodeRouteImport } from './routes/ferramentas/qr-code'
import { Route as QrWifiRouteImport } from './routes/ferramentas/qr-wifi'
import { Route as LinkBioRouteImport } from './routes/ferramentas/link-bio'
import { Route as LinkTemporarioRouteImport } from './routes/ferramentas/link-temporario'
import { Route as EncurtadorRouteImport } from './routes/ferramentas/encurtador'
import { Route as BotoesSiteRouteImport } from './routes/ferramentas/botoes-site'
import { Route as QrPersonalizadoRouteImport } from './routes/ferramentas/qr-personalizado'
import { Route as QrDinamicoRouteImport } from './routes/ferramentas/qr-dinamico'
import { Route as QrPixRouteImport } from './routes/ferramentas/qr-pix'
import { Route as PlacaPixRouteImport } from './routes/ferramentas/placa-pix'
import { Route as OrcamentoRouteImport } from './routes/ferramentas/orcamento'
import { Route as ReciboRouteImport } from './routes/ferramentas/recibo'
import { Route as CartaoDigitalRouteImport } from './routes/ferramentas/cartao-digital'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)

const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)

const LinkWhatsappRoute = LinkWhatsappRouteImport.update({
  id: '/ferramentas/link-whatsapp',
  path: '/ferramentas/link-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

const QrCodeRoute = QrCodeRouteImport.update({
  id: '/ferramentas/qr-code',
  path: '/ferramentas/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)

const QrWifiRoute = QrWifiRouteImport.update({
  id: '/ferramentas/qr-wifi',
  path: '/ferramentas/qr-wifi',
  getParentRoute: () => rootRouteImport,
} as any)

const LinkBioRoute = LinkBioRouteImport.update({
  id: '/ferramentas/link-bio',
  path: '/ferramentas/link-bio',
  getParentRoute: () => rootRouteImport,
} as any)

const LinkTemporarioRoute = LinkTemporarioRouteImport.update({
  id: '/ferramentas/link-temporario',
  path: '/ferramentas/link-temporario',
  getParentRoute: () => rootRouteImport,
} as any)

const EncurtadorRoute = EncurtadorRouteImport.update({
  id: '/ferramentas/encurtador',
  path: '/ferramentas/encurtador',
  getParentRoute: () => rootRouteImport,
} as any)

const BotoesSiteRoute = BotoesSiteRouteImport.update({
  id: '/ferramentas/botoes-site',
  path: '/ferramentas/botoes-site',
  getParentRoute: () => rootRouteImport,
} as any)

const QrPersonalizadoRoute = QrPersonalizadoRouteImport.update({
  id: '/ferramentas/qr-personalizado',
  path: '/ferramentas/qr-personalizado',
  getParentRoute: () => rootRouteImport,
} as any)

const QrDinamicoRoute = QrDinamicoRouteImport.update({
  id: '/ferramentas/qr-dinamico',
  path: '/ferramentas/qr-dinamico',
  getParentRoute: () => rootRouteImport,
} as any)

const QrPixRoute = QrPixRouteImport.update({
  id: '/ferramentas/qr-pix',
  path: '/ferramentas/qr-pix',
  getParentRoute: () => rootRouteImport,
} as any)

const PlacaPixRoute = PlacaPixRouteImport.update({
  id: '/ferramentas/placa-pix',
  path: '/ferramentas/placa-pix',
  getParentRoute: () => rootRouteImport,
} as any)

const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/ferramentas/orcamento',
  path: '/ferramentas/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)

const ReciboRoute = ReciboRouteImport.update({
  id: '/ferramentas/recibo',
  path: '/ferramentas/recibo',
  getParentRoute: () => rootRouteImport,
} as any)

const CartaoDigitalRoute = CartaoDigitalRouteImport.update({
  id: '/ferramentas/cartao-digital',
  path: '/ferramentas/cartao-digital',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ferramentas': typeof FerramentasRoute
  '/planos': typeof PlanosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramentas/link-whatsapp': typeof LinkWhatsappRoute
  '/ferramentas/qr-code': typeof QrCodeRoute
  '/ferramentas/qr-wifi': typeof QrWifiRoute
  '/ferramentas/qr-wifi': typeof QrWifiRoute
  '/ferramentas/link-bio': typeof LinkBioRoute
  '/ferramentas/link-temporario': typeof LinkTemporarioRoute
  '/ferramentas/encurtador': typeof EncurtadorRoute
  '/ferramentas/botoes-site': typeof BotoesSiteRoute
  '/ferramentas/qr-personalizado': typeof QrPersonalizadoRoute
  '/ferramentas/qr-dinamico': typeof QrDinamicoRoute
  '/ferramentas/qr-pix': typeof QrPixRoute
  '/ferramentas/placa-pix': typeof PlacaPixRoute
  '/ferramentas/orcamento': typeof OrcamentoRoute
  '/ferramentas/recibo': typeof ReciboRoute
  '/ferramentas/cartao-digital': typeof CartaoDigitalRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ferramentas': typeof FerramentasRoute
  '/planos': typeof PlanosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramentas/link-whatsapp': typeof LinkWhatsappRoute
  '/ferramentas/qr-code': typeof QrCodeRoute
  '/ferramentas/link-bio': typeof LinkBioRoute
  '/ferramentas/link-temporario': typeof LinkTemporarioRoute
  '/ferramentas/encurtador': typeof EncurtadorRoute
  '/ferramentas/botoes-site': typeof BotoesSiteRoute
  '/ferramentas/qr-personalizado': typeof QrPersonalizadoRoute
  '/ferramentas/qr-dinamico': typeof QrDinamicoRoute
  '/ferramentas/qr-pix': typeof QrPixRoute
  '/ferramentas/placa-pix': typeof PlacaPixRoute
  '/ferramentas/orcamento': typeof OrcamentoRoute
  '/ferramentas/recibo': typeof ReciboRoute
  '/ferramentas/cartao-digital': typeof CartaoDigitalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FerramentasRoute: typeof FerramentasRoute
  PlanosRoute: typeof PlanosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LinkWhatsappRoute: typeof LinkWhatsappRoute
  QrCodeRoute: typeof QrCodeRoute
  LinkBioRoute,
  LinkTemporarioRoute,
  EncurtadorRoute,
  BotoesSiteRoute,
  QrPersonalizadoRoute,
  QrDinamicoRoute,
  QrPixRoute,
  PlacaPixRoute,
  OrcamentoRoute,
  ReciboRoute,
  CartaoDigitalRoute,
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/link-whatsapp': {
      id: '/ferramentas/link-whatsapp'
      path: '/ferramentas/link-whatsapp'
      fullPath: '/ferramentas/link-whatsapp'
      preLoaderRoute: typeof LinkWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-code': {
      id: '/ferramentas/qr-code'
      path: '/ferramentas/qr-code'
      fullPath: '/ferramentas/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-wifi': {
      id: '/ferramentas/qr-wifi'
      path: '/ferramentas/qr-wifi'
      fullPath: '/ferramentas/qr-wifi'
      preLoaderRoute: typeof QrWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/link-bio': {
      id: '/ferramentas/link-bio'
      path: '/ferramentas/link-bio'
      fullPath: '/ferramentas/link-bio'
      preLoaderRoute: typeof LinkBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/link-temporario': {
      id: '/ferramentas/link-temporario'
      path: '/ferramentas/link-temporario'
      fullPath: '/ferramentas/link-temporario'
      preLoaderRoute: typeof LinkTemporarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/encurtador': {
      id: '/ferramentas/encurtador'
      path: '/ferramentas/encurtador'
      fullPath: '/ferramentas/encurtador'
      preLoaderRoute: typeof EncurtadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/botoes-site': {
      id: '/ferramentas/botoes-site'
      path: '/ferramentas/botoes-site'
      fullPath: '/ferramentas/botoes-site'
      preLoaderRoute: typeof BotoesSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-personalizado': {
      id: '/ferramentas/qr-personalizado'
      path: '/ferramentas/qr-personalizado'
      fullPath: '/ferramentas/qr-personalizado'
      preLoaderRoute: typeof QrPersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-dinamico': {
      id: '/ferramentas/qr-dinamico'
      path: '/ferramentas/qr-dinamico'
      fullPath: '/ferramentas/qr-dinamico'
      preLoaderRoute: typeof QrDinamicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/qr-pix': {
      id: '/ferramentas/qr-pix'
      path: '/ferramentas/qr-pix'
      fullPath: '/ferramentas/qr-pix'
      preLoaderRoute: typeof QrPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/placa-pix': {
      id: '/ferramentas/placa-pix'
      path: '/ferramentas/placa-pix'
      fullPath: '/ferramentas/placa-pix'
      preLoaderRoute: typeof PlacaPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/orcamento': {
      id: '/ferramentas/orcamento'
      path: '/ferramentas/orcamento'
      fullPath: '/ferramentas/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/recibo': {
      id: '/ferramentas/recibo'
      path: '/ferramentas/recibo'
      fullPath: '/ferramentas/recibo'
      preLoaderRoute: typeof ReciboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/cartao-digital': {
      id: '/ferramentas/cartao-digital'
      path: '/ferramentas/cartao-digital'
      fullPath: '/ferramentas/cartao-digital'
      preLoaderRoute: typeof CartaoDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRoute,
  DashboardRoute,
  FerramentasRoute,
  PlanosRoute,
  ComoFuncionaRoute,
  LinkWhatsappRoute,
  QrCodeRoute,
  QrWifiRoute,
  LinkBioRoute,
  LinkTemporarioRoute,
  EncurtadorRoute,
  BotoesSiteRoute,
  QrPersonalizadoRoute,
  QrDinamicoRoute,
  QrPixRoute,
  PlacaPixRoute,
  OrcamentoRoute,
  ReciboRoute,
  CartaoDigitalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
